name: Publish Docker image

on:
  push:
    branches:
      - ^v\d+\.\d+\.\d+$
  create:
    branches:
      - ^v\d+\.\d+\.\d+$

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      VERSION_BRANCHE: ""
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: front-end-react
            image: guyodokevin/frontend-react-cicd
          - context: order-service
            image: guyodokevin/backendorder-node-cicd
          - context: user-service
            image: guyodokevin/backenduser-python-cicd

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version number
        run: |
          # Récupérer le nom de la branche à partir de GITHUB_REF
          VERSION_BRANCHE=$(echo "${GITHUB_REF#refs/heads/}")

          # Extraire le numéro de version avec une regex
          if [[ "$VERSION_BRANCHE" =~ v([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            VERSION_NUMBER="${BASH_REMATCH[1]}"
            echo "Version number extracted from branch name: $VERSION_NUMBER"
          else
            echo "No version number found in branch name."
            exit 1
          fi


      - name: Build and Push Image
        run: |
          docker build -t ${{ matrix.image }}:$VERSION_BRANCHE ${{ matrix.context }}
          docker push ${{ matrix.image }}:$VERSION_BRANCHE