name: Publish Docker image

on:
  create:
    branches:
      - v\d+\.\d+\.\d+

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      VERSION_BRANCHE: ""
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: front-end-react
            image: jonesyluke859/front-end
          - context: order-service
            image: jonesyluke859/order-service
          - context: user-service
            image: jonesyluke859/user-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version number
        run: |
          # Get version branch value from GITHUB_REF
          echo "VERSION_BRANCHE=$(echo ${{ github.ref }} | sed 's/[^0-9.]*//g'))" >> $GITHUB_ENV

      - name: Build and Push Image
        run: |
          if [ -n "$VERSION_BRANCHE" ]; then
            docker build -t "${{ matrix.image }}:$VERSION_BRANCHE" ${{ matrix.context }}
            docker push "${{ matrix.image }}:$VERSION_BRANCHE"
          else
            echo "No version number found in branch name."
          fi
