name: Publish Docker image

on:
  push:
    branches:
      - ^d+\.\d+\.\d+$
  create:
    branches:
      - ^d+\.\d+\.\d+$

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: front-end-react
            image: jonesyluke859/front-end
          - context: order-service
            image: jonesyluke859/order-service
          - context: user-service
            image: jonesyluke859/user-service

    steps:
      - name: Extract version number
        id: extract_version
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed 's/[^0-9.]*//g')
          echo "::set-output name=version::$VERSION"
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME2 }}
          password: ${{ secrets.DOCKER_PASSWORD2 }}

      - name: Build and Push Image
        run: |
          docker build -t ${{ matrix.image }}:${{ steps.extract_version.outputs.version }} ${{ matrix.context }}
          docker push ${{ matrix.image }}:${{ steps.extract_version.outputs.version }}
