name: Publish Docker image

on:
  push:
    branches:
      - "main"
      - "dev_luke"
      - "dev_kevin"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - context: front-end-react
            image: guyodokevin/frontend-react-cicd
          - context: order-service
            image: guyodokevin/backendorder-node-cicd
          - context: user-service
            image: guyodokevin/backenduser-python-cicd

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image 
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.context }}
          push: true
          tags: ${{ matrix.image }}:latest

      # - name: Build and push image frontend react
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: ./frontend-react-cicd
      #     push: true
      #     tags: guyodokevin/frontend-react-cicd:latest

      # - name: Build and push image backend node
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: ./backendorder-node-cicd
      #     push: true
      #     tags: guyodokevin/backendorder-node-cicd:latest

      # - name: Build and push image backend python
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: ./backenduser-python-cicd
      #     push: true
      #     tags: guyodokevin/backenduser-python-cicd:latest