name: Publish Docker image

on:
  push:
    branches:
      - "main"
      - "dev_luke"
      - "dev_kevin"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image frontend react
        uses: docker/build-push-action@v5
        with:
          context: ./front-end-react
          push: true
          tags: guyodokevin/frontend-react-cicd:latest

      - name: Build and push image backend node
        uses: docker/build-push-action@v5
        with:
          context: ./order-service
          push: true
          tags: guyodokevin/backendorder-node-cicd:latest

      - name: Build and push image backend python
        uses: docker/build-push-action@v5
        with:
          context: ./user-service
          push: true
          tags: guyodokevin/backenduser-python-cicd:latest