name: Publish Docker image

on:
  push:
    branches:
      - ^v\d+\.\d+\.\d+$
  create:
    branches:
      - ^v\d+\.\d+\.\d+$

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: front-end-react
            image: guyodokevin/frontend-react-cicd
          - context: order-service
            image: guyodokevin/backendorder-node-cicd
          - context: user-service
            image: guyodokevin/backenduser-python-cicd

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract branch versions
        run: |
          BRANCH_NAME=$(echo $GITHUB_REF | grep -oE '^v\d+\.\d+\.\d+$')
          echo "Version extracted from branch name: $BRANCH_NAME"

      - name: Build and Push Image
        run: |
          docker build -t ${{ matrix.image }}:$BRANCH_NAME ${{ matrix.context }}
          docker push ${{ matrix.image }}:$BRANCH_NAME