name: Publish Docker image

on:
  push:
    branches:
      - "main"
      - "dev_luke"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: front-end-react
            image: jonesyluke859/front-react
          - context: order-service
            image: jonesyluke859/order-service-api
          - context: user-service
            image: jonesyluke859/user-service-python

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME2 }}
          password: ${{ secrets.DOCKER_PASSWORD2 }}

      - name: Build and Push Image
        run: |
          docker build -t ${{ matrix.image }}:latest ${{ matrix.context }}
          docker push ${{ matrix.image }}:latest
