name: Publish Docker image

on:
  push:
    branches:
      - ^v\d+\.\d+\.\d+$
  create:
    branches:
      - ^v\d+\.\d+\.\d+$

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      VERSION_BRANCHE: ""
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: front-end-react
            image: guyodokevin/frontend-react-cicd
          - context: order-service
            image: guyodokevin/backendorder-node-cicd
          - context: user-service
            image: guyodokevin/backenduser-python-cicd

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version number
        run: |
          # Récupérer le nom de la branche à partir de GITHUB_REF
          echo "VERSION_BRANCHE=$(echo ${{ github.ref }} | grep -oE '[1-9][0-9]*.[0-9]+.[0-9]+')" >> $GITHUB_ENV

      - name: Build and Push Image
        run: |
          if [ -n "$VERSION_BRANCHE" ]; then
            docker build -t "${{ matrix.image }}:$VERSION_BRANCHE" ${{ matrix.context }}
            docker push "${{ matrix.image }}:$VERSION_BRANCHE"
          else
            echo "No version number found in branch name."
          fi