name: Publish Docker image

on:
  push:
    branches:
      - "main"
      - "dev_luke"
      - "dev_kevin"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: front-end-react
            image: guyodokevin/frontend-react-cicd
          - context: order-service
            image: guyodokevin/backendorder-node-cicd
          - context: user-service
            image: guyodokevin/backenduser-python-cicd

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build and push to Docker Hub
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: ./${{ matrix.context }}
      #     push: true
      #     tags: ${{ matrix.image }}:${{ github.sha }}

      - name: Build and Push Frontend React Docker Image
        run: |
          docker build -t yourdockerhubusername/yourimage:latest front-end-react
          docker push guyodokevin/frontend-react-cicd:latest

      - name: Build and Push Backend Node Docker Image
        run: |
          docker build -t guyodokevin/backendorder-node-cicd:latest order-service
          docker push guyodokevin/backendorder-node-cicd:latest

      - name: Build and Push BackEnd Python Image
        run: |
          docker build -t guyodokevin/backenduser-python-cicd:latest user-service
          docker push guyodokevin/backenduser-python-cicd:latest